runtime: python39
entrypoint: streamlit run app.py --server.port $PORT --server.enableCORS false

env_variables:
  STREAMLIT_SERVER_HEADLESS: true
  STREAMLIT_SERVER_PORT: $PORT

automatic_scaling:
  min_instances: 0