[theme]
primaryColor="#161f36"
backgroundColor="#f2ede2"
secondaryBackgroundColor="#bacbd8"
textColor="#000000"
font="sans serif"

[server]
enableCORS = false
enableWebsocketCompression = false
enableXsrfProtection = false
headless = true